import { WmsAction, WmsSubjects } from './casl.types';

export interface PermissionEntry {
  action: WmsAction;
  subject: WmsSubjects;
}

export interface WmsRoleDefinition {
  roleCode: string;
  permissions: PermissionEntry[];
}

export const WMS_ROLE_DEFINITIONS: WmsRoleDefinition[] = [
  {
    roleCode: 'WAREHOUSE_ADMIN',
    permissions: [
      { action: WmsAction.Manage, subject: 'WarehouseFacility' },
      { action: WmsAction.Manage, subject: 'WarehouseZone' },
      { action: WmsAction.Manage, subject: 'StorageLocation' },
      { action: WmsAction.Manage, subject: 'Product' },
      { action: WmsAction.Manage, subject: 'ProductCategory' },
      { action: WmsAction.Manage, subject: 'UnitOfMeasure' },
      { action: WmsAction.Manage, subject: 'ProductAttribute' },
      { action: WmsAction.Manage, subject: 'ProductBarcode' },
      { action: WmsAction.Manage, subject: 'Inventory' },
      { action: WmsAction.Manage, subject: 'LPN' },
      { action: WmsAction.Manage, subject: 'SalesOrder' },
      { action: WmsAction.Manage, subject: 'PurchaseOrder' },
      { action: WmsAction.Manage, subject: 'Task' },
      { action: WmsAction.Manage, subject: 'CycleCount' },
      { action: WmsAction.Manage, subject: 'Adjustment' },
      { action: WmsAction.Manage, subject: 'Report' },
      { action: WmsAction.Manage, subject: 'InventoryOnHand' },
      { action: WmsAction.Manage, subject: 'InventoryTransaction' },
      { action: WmsAction.Manage, subject: 'InventoryLot' },
      { action: WmsAction.Manage, subject: 'InventoryHold' },
      { action: WmsAction.Manage, subject: 'InventoryAdjustment' },
      { action: WmsAction.Manage, subject: 'InventoryPolicy' },
      { action: WmsAction.Manage, subject: 'AdvanceShipNotice' },
      { action: WmsAction.Manage, subject: 'GoodsReceipt' },
      { action: WmsAction.Manage, subject: 'LPN' },
      { action: WmsAction.Manage, subject: 'PutawayTask' },
      { action: WmsAction.Manage, subject: 'Inspection' },
      { action: WmsAction.Manage, subject: 'QcDisposition' },
      { action: WmsAction.Manage, subject: 'SalesOrder' },
      { action: WmsAction.Manage, subject: 'InventoryAllocation' },
      { action: WmsAction.Manage, subject: 'PickingWave' },
      { action: WmsAction.Manage, subject: 'PickingTask' },
      { action: WmsAction.Manage, subject: 'PackingSession' },
      { action: WmsAction.Manage, subject: 'PackingContainer' },
      { action: WmsAction.Manage, subject: 'OutboundShipment' },
      { action: WmsAction.Reallocate, subject: 'Inventory' },
      { action: WmsAction.Cancel, subject: 'OutboundShipment' },
      { action: WmsAction.Manage, subject: 'InventoryTransfer' },
      { action: WmsAction.Manage, subject: 'InventoryTransferLine' },
      { action: WmsAction.Manage, subject: 'CycleCount' },
      { action: WmsAction.Manage, subject: 'CycleCountLine' },
      { action: WmsAction.Manage, subject: 'AdjustmentApproval' },
      { action: WmsAction.Manage, subject: 'ApprovalThresholdConfig' },
      { action: WmsAction.OverrideApproval, subject: 'AdjustmentApproval' },
    ],
  },
  {
    roleCode: 'WAREHOUSE_SUPERVISOR',
    permissions: [
      { action: WmsAction.Read, subject: 'all' },
      { action: WmsAction.Read, subject: 'Product' },
      { action: WmsAction.Update, subject: 'Product' },
      { action: WmsAction.Approve, subject: 'Adjustment' },
      { action: WmsAction.Approve, subject: 'CycleCount' },
      { action: WmsAction.Approve, subject: 'Task' },
      { action: WmsAction.Adjust, subject: 'Inventory' },
      { action: WmsAction.Adjust, subject: 'StorageLocation' },
      { action: WmsAction.Count, subject: 'CycleCount' },
      { action: WmsAction.Receive, subject: 'PurchaseOrder' },
      { action: WmsAction.Pick, subject: 'SalesOrder' },
      { action: WmsAction.Pack, subject: 'SalesOrder' },
      { action: WmsAction.Ship, subject: 'SalesOrder' },
      { action: WmsAction.Approve, subject: 'InventoryAdjustment' },
      { action: WmsAction.Receive, subject: 'GoodsReceipt' },
      { action: WmsAction.Receive, subject: 'LPN' },
      { action: WmsAction.ExecutePutaway, subject: 'PutawayTask' },
      { action: WmsAction.PerformQc, subject: 'Inspection' },
      { action: WmsAction.Approve, subject: 'QcDisposition' },
      { action: WmsAction.Release, subject: 'PickingWave' },
      { action: WmsAction.Approve, subject: 'InventoryAllocation' },
      { action: WmsAction.ShortPick, subject: 'PickingTask' },
      { action: WmsAction.Approve, subject: 'AdjustmentApproval' },
      { action: WmsAction.ManageCycleCountSchedule, subject: 'all' },
    ],
  },
  {
    roleCode: 'WAREHOUSE_OPERATOR',
    permissions: [
      { action: WmsAction.Read, subject: 'Product' },
      { action: WmsAction.Read, subject: 'ProductCategory' },
      { action: WmsAction.Read, subject: 'UnitOfMeasure' },
      { action: WmsAction.Read, subject: 'WarehouseFacility' },
      { action: WmsAction.Read, subject: 'WarehouseZone' },
      { action: WmsAction.Read, subject: 'StorageLocation' },
      { action: WmsAction.Read, subject: 'Inventory' },
      { action: WmsAction.Read, subject: 'LPN' },
      { action: WmsAction.Read, subject: 'SalesOrder' },
      { action: WmsAction.Read, subject: 'PurchaseOrder' },
      { action: WmsAction.Receive, subject: 'PurchaseOrder' },
      { action: WmsAction.Pick, subject: 'SalesOrder' },
      { action: WmsAction.Pack, subject: 'SalesOrder' },
      { action: WmsAction.Ship, subject: 'SalesOrder' },
      { action: WmsAction.Adjust, subject: 'Inventory' },
      { action: WmsAction.Transact, subject: 'Inventory' },
      { action: WmsAction.Pick, subject: 'PickingTask' },
      { action: WmsAction.Pack, subject: 'PackingSession' },
      { action: WmsAction.Read, subject: 'SalesOrder' },
      { action: WmsAction.ExecuteCycleCount, subject: 'CycleCount' },
      { action: WmsAction.InitiateTransfer, subject: 'InventoryTransfer' },
      { action: WmsAction.ReceiveTransfer, subject: 'InventoryTransfer' },
    ],
  },
  {
    roleCode: 'INVENTORY_CLERK',
    permissions: [
      { action: WmsAction.Read, subject: 'Product' },
      { action: WmsAction.Create, subject: 'Product' },
      { action: WmsAction.Read, subject: 'ProductCategory' },
      { action: WmsAction.Read, subject: 'UnitOfMeasure' },
      { action: WmsAction.Manage, subject: 'ProductAttribute' },
      { action: WmsAction.Read, subject: 'StorageLocation' },
      { action: WmsAction.Read, subject: 'Inventory' },
      { action: WmsAction.Count, subject: 'CycleCount' },
      { action: WmsAction.Adjust, subject: 'Inventory' },
      { action: WmsAction.Adjust, subject: 'StorageLocation' },
      { action: WmsAction.Manage, subject: 'InventoryOnHand' },
      { action: WmsAction.Manage, subject: 'InventoryLot' },
    ],
  },
];

export const ALL_WMS_SUBJECTS: WmsSubjects[] = [
  'WarehouseFacility',
  'WarehouseZone',
  'StorageLocation',
  'Product',
  'ProductCategory',
  'UnitOfMeasure',
  'ProductAttribute',
  'ProductBarcode',
  'Inventory',
  'LPN',
  'SalesOrder',
  'PurchaseOrder',
  'Task',
  'CycleCount',
  'Adjustment',
  'Report',
  'InventoryOnHand',
  'InventoryTransaction',
  'InventoryLot',
  'InventoryHold',
  'InventoryAdjustment',
  'InventoryPolicy',
  'AdvanceShipNotice',
  'GoodsReceipt',
  'LPN',
  'PutawayTask',
  'Inspection',
  'QcDisposition',
  'SalesOrder',
  'InventoryAllocation',
  'PickingWave',
  'PickingTask',
  'PackingSession',
  'PackingContainer',
  'OutboundShipment',
  'InventoryTransfer',
  'InventoryTransferLine',
  'CycleCount',
  'CycleCountLine',
  'AdjustmentApproval',
  'ApprovalThresholdConfig',
];

export const ALL_WMS_ACTIONS: WmsAction[] = Object.values(WmsAction);
