import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../prisma/prisma.service';

@Injectable()
export class ReportsService {
  private readonly logger = new Logger(ReportsService.name);

  constructor(private readonly prisma: PrismaService) {}

  async createJob(tenantId: string, dto: {
    reportType: string;
    parameters?: Record<string, any>;
  }) {
    const paramsJson = JSON.stringify(dto.parameters || {});
    // The wms_report_jobs table uses UUID for id (generated by gen_random_uuid())
    const rows = await this.prisma.$queryRawUnsafe<Record<string, any>[]>(
      `INSERT INTO multitenant.wms_report_jobs
         (tenant_id, report_type, parameters, status, created_at, updated_at)
       VALUES ($1::uuid, $2, $3::jsonb, 'PENDING', NOW(), NOW())
       RETURNING *`,
      tenantId,
      dto.reportType,
      paramsJson,
    );
    return rows[0];
  }

  async findAllJobs(tenantId: string, query: any = {}) {
    const page = Number(query.page) || 1;
    const limit = Number(query.limit) || 50;
    const conditions: string[] = ['tenant_id = $1::uuid'];
    const params: any[] = [tenantId];
    let idx = 2;

    if (query.reportType) {
      conditions.push(`report_type = $${idx}`);
      params.push(query.reportType);
      idx++;
    }
    if (query.status) {
      conditions.push(`status = $${idx}`);
      params.push(query.status);
      idx++;
    }

    const where = `WHERE ${conditions.join(' AND ')}`;
    const countResult = await this.prisma.$queryRawUnsafe<Record<string, any>[]>(
      `SELECT COUNT(*) AS total FROM multitenant.wms_report_jobs ${where}`, ...params,
    );
    const rows = await this.prisma.$queryRawUnsafe<Record<string, any>[]>(
      `SELECT * FROM multitenant.wms_report_jobs ${where}
       ORDER BY created_at DESC
       LIMIT $${idx} OFFSET $${idx + 1}`,
      ...params, limit, (page - 1) * limit,
    );
    return { data: rows, total: Number(countResult[0]?.total || 0), page, limit };
  }

  async deleteJob(tenantId: string, id: string) {
    await this.prisma.$executeRawUnsafe(
      `DELETE FROM multitenant.wms_report_jobs WHERE tenant_id = $1::uuid AND id = $2::uuid`,
      tenantId, id,
    );
    return { message: 'Report job deleted successfully' };
  }

  async findJobById(tenantId: string, id: string) {
    const rows = await this.prisma.$queryRawUnsafe<Record<string, any>[]>(
      `SELECT * FROM multitenant.wms_report_jobs WHERE tenant_id = $1::uuid AND id = $2::uuid`,
      tenantId, id,
    );
    return rows.length ? rows[0] : null;
  }

  async updateJob(id: string, status: string, result?: { downloadUrl?: string; rowCount?: number; errorMessage?: string }) {
    const rows = await this.prisma.$queryRawUnsafe<Record<string, any>[]>(
      `UPDATE multitenant.wms_report_jobs
       SET status = $1,
           download_url = COALESCE($2, download_url),
           row_count = COALESCE($3, row_count),
           error_message = COALESCE($4, error_message),
           expires_at = CASE WHEN $1 = 'COMPLETED' THEN NOW() + INTERVAL '7 days' ELSE expires_at END,
           updated_at = NOW()
       WHERE id = $5::uuid
       RETURNING *`,
      status,
      result?.downloadUrl || null,
      result?.rowCount || null,
      result?.errorMessage || null,
      id,
    );
    return rows[0];
  }

  /** Generate real inventory aging report from DB */
  async generateInventoryAgingReport(tenantId: string, facilityId?: string): Promise<any[]> {
    const facilityClause = facilityId ? `AND ioh.facility_id = $2::bigint` : '';
    const params: any[] = [tenantId];
    if (facilityId) params.push(BigInt(facilityId));

    return this.prisma.$queryRawUnsafe<Record<string, any>[]>(
      `SELECT
         ioh.product_id,
         p.product_code,
         p.product_name,
         ioh.lot_id,
         il.lot_number,
         il.received_date,
         il.expiry_date,
         ioh.location_id,
         sl.location_code,
         ioh.quantity_on_hand,
         CASE
           WHEN il.received_date IS NULL THEN 'UNKNOWN'
           WHEN il.received_date < CURRENT_DATE - INTERVAL '90 days' THEN '90+ DAYS'
           WHEN il.received_date < CURRENT_DATE - INTERVAL '60 days' THEN '61-90 DAYS'
           WHEN il.received_date < CURRENT_DATE - INTERVAL '30 days' THEN '31-60 DAYS'
           ELSE '0-30 DAYS'
         END AS aging_bucket,
         CURRENT_DATE - il.received_date AS days_in_storage
       FROM multitenant.inventory_on_hand ioh
       JOIN multitenant.products p ON ioh.product_id = p.product_id
       LEFT JOIN multitenant.inventory_lots il ON ioh.lot_id = il.lot_id
       LEFT JOIN multitenant.storage_locations sl ON ioh.location_id = sl.location_id
       WHERE ioh.tenant_id = $1::uuid AND ioh.quantity_on_hand > 0
       ${facilityClause}
       ORDER BY il.received_date ASC NULLS LAST`,
      ...params,
    );
  }

  /** Generate pick heatmap report */
  async generatePickHeatmapReport(tenantId: string, facilityId?: string, days?: number): Promise<any[]> {
    const lookbackDays = days || 30;
    const facilityClause = facilityId ? `AND lph.facility_id = $2::bigint` : '';
    const params: any[] = [tenantId, lookbackDays];
    if (facilityId) params.splice(1, 0, BigInt(facilityId));

    return this.prisma.$queryRawUnsafe<Record<string, any>[]>(
      `SELECT
         lph.location_id,
         sl.location_code,
         sl.location_type,
         SUM(lph.total_picks) AS total_picks,
         AVG(lph.pick_density_score) AS avg_density_score,
         COUNT(DISTINCT lph.product_id) AS unique_products_picked
       FROM multitenant.location_pick_heatmap lph
       LEFT JOIN multitenant.storage_locations sl ON lph.location_id = sl.location_id
       WHERE lph.tenant_id = $1::uuid
         AND lph.snapshot_date >= CURRENT_DATE - $2::integer
       ${facilityClause}
       GROUP BY lph.location_id, sl.location_code, sl.location_type
       ORDER BY total_picks DESC`,
      ...params,
    );
  }

  /** Generate cycle count accuracy report */
  async generateCycleCountAccuracyReport(tenantId: string, facilityId?: string): Promise<any[]> {
    const facilityClause = facilityId ? `AND ic.facility_id = $2::bigint` : '';
    const params: any[] = [tenantId];
    if (facilityId) params.push(BigInt(facilityId));

    return this.prisma.$queryRawUnsafe<Record<string, any>[]>(
      `SELECT
         ic.count_id,
         ic.count_number,
         ic.completed_at,
         ic.total_items_counted,
         ic.total_variances,
         ic.accuracy_percentage,
         CASE
           WHEN ic.accuracy_percentage >= 98 THEN 'EXCELLENT'
           WHEN ic.accuracy_percentage >= 95 THEN 'GOOD'
           WHEN ic.accuracy_percentage >= 90 THEN 'FAIR'
           ELSE 'POOR'
         END AS accuracy_rating
       FROM multitenant.inventory_counts ic
       WHERE ic.tenant_id = $1::uuid AND ic.status = 'COMPLETED'
       ${facilityClause}
       ORDER BY ic.completed_at DESC
       LIMIT 100`,
      ...params,
    );
  }
}
