import { Injectable, Logger, BadRequestException, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import { investigation_status } from '@prisma/client';
import { CycleCountThresholdService } from './cycle-count-threshold.service';

@Injectable()
export class CycleCountService {
  private readonly logger = new Logger(CycleCountService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly thresholdService: CycleCountThresholdService,
  ) {}

  private mapCamelToSnake(dto: any): any {
    const map: Record<string, string> = {
      facilityId: 'facility_id',
      countNumber: 'count_number',
      countName: 'count_name',
      countScopeType: 'count_scope_type',
      countScopeIdentifier: 'count_scope_identifier',
      countMethod: 'count_method',
      countPriority: 'count_priority',
      countFrequencyType: 'count_frequency_type',
      countFrequencyValue: 'count_frequency_value',
      samplingMethod: 'sampling_method',
      sampleSizePercentage: 'sample_size_percentage',
      accuracyPercentage: 'accuracy_percentage',
      scheduledDate: 'scheduled_date',
      startedAt: 'started_at',
      completedAt: 'completed_at',
      assignedToUserId: 'assigned_to_user_id',
      varianceThresholdPercentage: 'variance_threshold_percentage',
      autoAdjustOnVariance: 'auto_adjust_on_variance',
      totalItemsCounted: 'total_items_counted',
      totalVarianceQuantity: 'total_variance_quantity',
      autoGenerated: 'auto_generated',
      lastAutoGeneratedDate: 'last_auto_generated_date',
      nextScheduledDate: 'next_scheduled_date',
      isBlindCount: 'is_blind_count',
      parentCountId: 'parent_count_id',
      countType: 'count_type',
      excludedUserId: 'excluded_user_id',
      userId: 'created_by',
    };
    const result: any = {};
    for (const [key, val] of Object.entries(dto)) {
      const snake = map[key] || key;
      if (val === undefined || val === null) continue;
      if (key === 'facilityId' || key === 'countScopeIdentifier' || key === 'facility_id' || key === 'parentCountId') {
        result[snake] = typeof val === 'bigint' ? val : BigInt(val as string | number | bigint | boolean);
      } else {
        result[snake] = val;
      }
    }
    return result;
  }

  // APP-CC-E: Immutable audit trail
  private async logEvent(tenantId: string, facilityId: bigint, countId: bigint, eventType: string, performedBy: string | null, data?: any) {
    try {
      await this.prisma.cycle_count_events.create({
        data: {
          tenant_id: tenantId,
          facility_id: facilityId,
          count_id: countId,
          event_type: eventType,
          event_data: data ? JSON.stringify(data) : null,
          performed_by: performedBy || null,
          performed_at: new Date(),
        },
      });
    } catch (err) {
      this.logger.warn(`Failed to log cycle count event: ${(err as Error).message}`);
    }
  }

  async delete(tenantId: string, id: bigint) {
    return this.prisma.inventory_counts.deleteMany({
      where: { tenant_id: tenantId, count_id: id },
    });
  }

  // APP-CC-K: Ad-hoc count creation
  async create(tenantId: string, dto: any) {
    const data = this.mapCamelToSnake({ ...dto, tenant_id: tenantId });
    if (!data.status) data.status = 'PENDING';
    if (data.is_blind_count === undefined) data.is_blind_count = true;
    if (!data.count_type) data.count_type = 'ORIGINAL';
    const created = await this.prisma.inventory_counts.create({ data });
    await this.logEvent(tenantId, created.facility_id, created.count_id, 'COUNT_CREATED', data.created_by || null, { countNumber: created.count_number });
    return created;
  }

  // APP-CC-K: Ad-hoc count creation helper
  async createAdHoc(tenantId: string, dto: any) {
    return this.create(tenantId, {
      ...dto,
      countType: 'ADHOC',
      countMethod: 'SPOT',
    });
  }

  async findAll(tenantId: string, query: any) {
    const { status, facilityId, page = 1, limit = 50 } = query;
    const skip = (page - 1) * limit;
    const where: any = { tenant_id: tenantId };
    if (status) where.status = status;
    if (facilityId) where.facility_id = BigInt(facilityId);
    const [data, total] = await Promise.all([
      this.prisma.inventory_counts.findMany({
        where, skip, take: limit, orderBy: { created_at: 'desc' },
      }),
      this.prisma.inventory_counts.count({ where }),
    ]);
    return { data, total, page, limit };
  }

  async findById(tenantId: string, id: string) {
    return this.prisma.inventory_counts.findFirst({
      where: { tenant_id: tenantId, count_id: BigInt(id) },
    });
  }

  async update(tenantId: string, id: string, dto: any) {
    await this.findById(tenantId, id);
    const data = this.mapCamelToSnake(dto);
    return this.prisma.inventory_counts.update({
      where: { count_id: BigInt(id) },
      data,
    });
  }

  // APP-CC-F: getNextCountWork with collision prevention via optimistic locking
  async getNextCountWork(tenantId: string, facilityId: bigint, userId: string) {
    // GAP-3.2: Prioritize recounts but exclude original counter
    const candidates = await this.prisma.inventory_counts.findMany({
      where: { tenant_id: tenantId, facility_id: facilityId, status: { in: ['READY', 'PENDING'] } },
      orderBy: [{ count_priority: 'asc' }, { created_at: 'asc' }],
      take: 10,
    });
    for (const count of candidates) {
      // GAP-3.2: Exclude original counter for recounts
      if (count.excluded_user_id && count.excluded_user_id === userId) continue;
      // APP-CC-F: Optimistic locking — atomically set ASSIGNED
      const updated = await this.prisma.inventory_counts.updateMany({
        where: {
          count_id: count.count_id,
          tenant_id: tenantId,
          status: count.status,
        },
        data: {
          status: 'ASSIGNED',
          assigned_to_user_id: userId,
          version: (count.version || BigInt(0)) + BigInt(1),
        },
      });
      if (updated.count > 0) {
        await this.logEvent(tenantId, facilityId, count.count_id, 'COUNT_ASSIGNED', userId, { userId });
        return this.findById(tenantId, count.count_id.toString());
      }
    }
    return null;
  }

  // APP-CC-B: Location scan validation & rejection
  async scanLocationForCount(tenantId: string, facilityId: bigint, locationBarcode: string, countId?: string) {
    const location = await this.prisma.storage_locations.findFirst({
      where: {
        tenant_id: tenantId, facility_id: facilityId,
        OR: [{ location_code: locationBarcode }, { barcode_value: locationBarcode }],
      },
    });
    if (!location) throw new NotFoundException('Location not found');

    // APP-CC-B: Validate scanned location against expected location
    if (countId) {
      const count = await this.findById(tenantId, countId);
      if (count?.count_scope_identifier && count.count_scope_type === 'LOCATION') {
        const expectedLocId = BigInt(count.count_scope_identifier);
        if (expectedLocId !== location.location_id) {
          const expected = await this.prisma.storage_locations.findFirst({
            where: { tenant_id: tenantId, location_id: expectedLocId },
          });
          throw new BadRequestException(`WRONG LOCATION — Expected: ${expected?.location_code || expectedLocId}, Scanned: ${location.location_code}`);
        }
      }
    }

    const lpns = await this.prisma.license_plate_numbers.findMany({
      where: { tenant_id: tenantId, facility_id: facilityId, location_id: location.location_id },
      select: { lpn_id: true, lpn_number: true, product_id: true },
    });
    const onHand = await this.prisma.inventory_on_hand.findMany({
      where: { tenant_id: tenantId, facility_id: facilityId, location_id: location.location_id },
    });
    const productIds = new Set<bigint>();
    lpns.forEach((l) => { if (l.product_id) productIds.add(l.product_id); });
    onHand.forEach((o) => productIds.add(o.product_id));
    const products = productIds.size > 0
      ? await this.prisma.products.findMany({
          where: { tenant_id: tenantId, product_id: { in: Array.from(productIds) } },
          select: { product_id: true, product_code: true, product_name: true, is_sensitive: true, sensitivity_level: true },
        })
      : [];

    // GAP-8: Blind count toggle — only return systemQty if is_blind_count=false
    const countForBlind = countId ? await this.findById(tenantId, countId) : null;
    const isBlind = countForBlind?.is_blind_count !== false;
    const items = onHand.map((o) => {
      const product = products.find((p) => p.product_id === o.product_id);
      return {
        productId: o.product_id.toString(),
        productCode: product?.product_code || null,
        productName: product?.product_name || null,
        lpnNumber: lpns.find((l) => l.product_id === o.product_id)?.lpn_number || null,
        ...(isBlind ? {} : { expectedQuantity: Number(o.quantity_on_hand) }),
        isSensitive: product?.is_sensitive || false,
        sensitivityLevel: product?.sensitivity_level || 'NORMAL',
      };
    });

    if (countId) {
      await this.logEvent(tenantId, facilityId, BigInt(countId), 'LOCATION_SCANNED', null, { locationCode: location.location_code });
    }
    return { locationId: location.location_id.toString(), locationCode: location.location_code, barcodeValue: location.barcode_value, items, itemCount: items.length, isBlindCount: isBlind };
  }

  async verifyItemAtLocation(tenantId: string, facilityId: bigint, locationBarcode: string, lpnBarcode: string) {
    const location = await this.prisma.storage_locations.findFirst({
      where: { tenant_id: tenantId, facility_id: facilityId, OR: [{ location_code: locationBarcode }, { barcode_value: locationBarcode }] },
    });
    if (!location) throw new Error('Location not found');
    const lpn = await this.prisma.license_plate_numbers.findFirst({
      where: { tenant_id: tenantId, facility_id: facilityId, lpn_number: lpnBarcode, location_id: location.location_id },
    });
    if (lpn) {
      const product = lpn.product_id ? await this.prisma.products.findFirst({ where: { tenant_id: tenantId, product_id: lpn.product_id } }) : null;
      return { verified: true, matchType: 'LPN', lpn, product };
    }
    let product = await this.prisma.products.findFirst({ where: { tenant_id: tenantId, product_code: lpnBarcode } });
    if (!product) {
      const pb = await this.prisma.product_barcodes.findFirst({ where: { tenant_id: tenantId, barcode_value: lpnBarcode }, include: { products: true } });
      product = pb?.products || null;
    }
    if (product) {
      const onHand = await this.prisma.inventory_on_hand.findFirst({ where: { tenant_id: tenantId, facility_id: facilityId, product_id: product.product_id, location_id: location.location_id } });
      if (onHand) return { verified: true, matchType: 'PRODUCT', product, onHandQty: Number(onHand.quantity_on_hand) };
    }
    throw new Error('Scanned barcode does not match any LPN or product at this location');
  }

  // GAP-7: LPN counting mode
  async startLpnCount(tenantId: string, facilityId: bigint, lpnBarcode: string, userId: string) {
    const lpn = await this.prisma.license_plate_numbers.findFirst({
      where: { tenant_id: tenantId, facility_id: facilityId, lpn_number: lpnBarcode },
    });
    if (!lpn) throw new NotFoundException(`LPN ${lpnBarcode} not found`);
    const count = await this.create(tenantId, {
      facilityId: Number(facilityId),
      countNumber: `LPN-CC-${lpnBarcode}-${Date.now()}`,
      countName: `LPN Count for ${lpnBarcode}`,
      countScopeType: 'LPN',
      countScopeIdentifier: Number(lpn.lpn_id),
      status: 'ASSIGNED',
      assignedToUserId: userId,
      isBlindCount: true,
    });
    const onHand = await this.prisma.inventory_on_hand.findMany({
      where: { tenant_id: tenantId, facility_id: facilityId, product_id: lpn.product_id || undefined },
    });
    const products = onHand.length > 0
      ? await this.prisma.products.findMany({ where: { tenant_id: tenantId, product_id: { in: onHand.map(o => o.product_id) } }, select: { product_id: true, product_code: true, product_name: true } })
      : [];
    const items = onHand.map(o => {
      const p = products.find(p => p.product_id === o.product_id);
      return { productId: o.product_id.toString(), productCode: p?.product_code || null, productName: p?.product_name || null };
    });
    await this.logEvent(tenantId, facilityId, count.count_id, 'LPN_COUNT_STARTED', userId, { lpnBarcode });
    return { count, items, lpn };
  }

  // APP-CC-G: Save draft line
  async saveDraftLine(tenantId: string, countId: string, dto: any) {
    const count = await this.findById(tenantId, countId);
    if (!count) throw new NotFoundException('Count not found');
    const existing = await this.prisma.inventory_count_lines.findFirst({
      where: { tenant_id: tenantId, count_id: BigInt(countId), product_id: BigInt(dto.productId), is_final: false },
    });
    if (existing) {
      return this.prisma.inventory_count_lines.update({
        where: { count_line_id: existing.count_line_id },
        data: { draft_quantity: dto.countedQuantity || dto.quantity, notes: dto.notes || existing.notes },
      });
    }
    return this.prisma.inventory_count_lines.create({
      data: {
        tenant_id: tenantId, facility_id: count.facility_id, count_id: BigInt(countId),
        product_id: BigInt(dto.productId), location_id: BigInt(dto.locationId || count.count_scope_identifier || 0),
        counted_quantity: 0, system_quantity: 0, draft_quantity: dto.countedQuantity || dto.quantity,
        is_final: false, counted_by_user_id: dto.userId || null, notes: dto.notes || null,
      },
    });
  }

  // APP-CC-G: Get count progress
  async getCountProgress(tenantId: string, countId: string) {
    const lines = await this.prisma.inventory_count_lines.findMany({
      where: { tenant_id: tenantId, count_id: BigInt(countId) },
    });
    return { counted: lines.filter(l => l.is_final).length, draft: lines.filter(l => !l.is_final).length, total: lines.length };
  }

  // GAP-1.3: submitLine with threshold integration + APP-CC-D sensitive inventory + APP-CC-H zero-count
  async submitLine(tenantId: string, countId: string, dto: any) {
    const count = await this.findById(tenantId, countId);
    if (!count) throw new NotFoundException('Count not found');
    const facilityId = dto.facilityId ? BigInt(dto.facilityId) : count.facility_id;

    const systemQty = dto.systemQuantity || await this.getSystemQuantity(tenantId, BigInt(dto.productId), BigInt(dto.locationId), dto.lotId ? BigInt(dto.lotId) : null);
    const countedQty = Number(dto.countedQuantity || dto.quantity || 0);
    const variance = Math.abs(countedQty - systemQty);
    const variancePct = systemQty > 0 ? (variance / systemQty) * 100 : 100;

    // GAP-1.3: Use threshold service instead of hardcoded 5%
    const thresholdEval = await this.thresholdService.evaluateVariance(tenantId, facilityId, systemQty, countedQty);

    // APP-CC-D: Sensitive inventory — always require supervisor review
    const product = await this.prisma.products.findFirst({ where: { tenant_id: tenantId, product_id: BigInt(dto.productId) } });
    const isSensitive = product?.is_sensitive || false;
    if (isSensitive && variance > 0) {
      thresholdEval.action = 'SUPERVISOR_REVIEW';
      thresholdEval.reason = 'Sensitive inventory — supervisor review required for any variance';
    }

    // APP-CC-H: Zero-count / empty location handling
    const isEmptyLocation = countedQty === 0 && systemQty > 0;

    // APP-CC-C: Repeated variance detection
    const repeatCount = await this.prisma.variance_investigations.count({
      where: { tenant_id: tenantId, product_id: BigInt(dto.productId), location_id: BigInt(dto.locationId), status: { in: [investigation_status.OPEN, investigation_status.RESOLVED] } },
    });
    const isRepeatVariance = repeatCount >= 3;

    const line = await this.prisma.inventory_count_lines.create({
      data: {
        tenant_id: tenantId, facility_id: facilityId, count_id: BigInt(countId),
        product_id: BigInt(dto.productId), location_id: BigInt(dto.locationId),
        ...(dto.lotId ? { lot_id: BigInt(dto.lotId) } : {}),
        counted_quantity: countedQty, system_quantity: systemQty,
        counted_by_user_id: dto.userId || null, notes: dto.notes || null,
        is_final: true, is_repeat_variance: isRepeatVariance,
        count_round: count.count_type === 'RECOUNT' ? 2 : (count.count_type === 'TRIPLE_COUNT' ? 3 : 1),
      },
    });

    await this.logEvent(tenantId, facilityId, BigInt(countId), 'QUANTITY_SUBMITTED', dto.userId || null, { countedQty, systemQty, variance });

    const matchStatus = variance === 0 ? 'MATCH' : (thresholdEval.action === 'AUTO_APPROVE' ? 'MATCH' : 'MISMATCH');
    return {
      line,
      matchStatus,
      systemQty, countedQty, variance, variancePct,
      thresholdAction: thresholdEval.action,
      thresholdReason: thresholdEval.reason,
      autoApproved: thresholdEval.action === 'AUTO_APPROVE',
      requiresRecount: thresholdEval.action === 'RECOUNT',
      requiresSupervisorApproval: thresholdEval.action === 'SUPERVISOR_REVIEW',
      isSensitiveInventory: isSensitive,
      isEmptyLocation,
      isRepeatVariance,
      repeatVarianceCount: repeatCount,
    };
  }

  // GAP-1.3 + GAP-2.1 + GAP-3.1 + APP-CC-A: complete with threshold, adjustments, auto-recount, state machine
  async complete(tenantId: string, id: string, userId: string, facilityId?: string) {
    const count = await this.findById(tenantId, id);
    if (!count) throw new NotFoundException('Cycle count not found');
    if (count.status === 'COMPLETED' || count.status === 'CLOSED') throw new BadRequestException('Cycle count already completed');

    const lines = await this.prisma.inventory_count_lines.findMany({
      where: { tenant_id: tenantId, count_id: BigInt(id) },
    });

    let totalVarianceQty = 0;
    let varianceLines = 0;
    let autoApprovedLines = 0;

    for (const line of lines) {
      const systemQty = await this.getSystemQuantity(tenantId, line.product_id, line.location_id, line.lot_id);
      const countedQty = Number(line.counted_quantity || 0);
      const variance = Math.abs(countedQty - systemQty);

      await this.prisma.inventory_count_lines.update({
        where: { count_line_id: line.count_line_id },
        data: { system_quantity: systemQty },
      });

      if (variance === 0) {
        // Exact match — auto-approve
        autoApprovedLines++;
        await this.prisma.inventory_count_lines.update({
          where: { count_line_id: line.count_line_id },
          data: { status: 'APPROVED', approved_by: userId, approved_at: new Date() },
        });
        continue;
      }

      // GAP-1.3: Use threshold service
      const thresholdEval = await this.thresholdService.evaluateVariance(tenantId, count.facility_id, systemQty, countedQty);

      if (thresholdEval.action === 'AUTO_APPROVE' && variance > 0) {
        // GAP-2.1: Auto-approve — adjust inventory + create inventory_adjustments record
        autoApprovedLines++;
        await this.applyInventoryAdjustment(tenantId, count.facility_id, line, systemQty, countedQty, variance, userId, 'AUTO_APPROVE');
        await this.prisma.inventory_count_lines.update({
          where: { count_line_id: line.count_line_id },
          data: { status: 'APPROVED', approved_by: userId, approved_at: new Date() },
        });
        await this.logEvent(tenantId, count.facility_id, BigInt(id), 'AUTO_APPROVED', userId, { lineId: line.count_line_id, variance });
      } else {
        // Create variance investigation
        totalVarianceQty += variance;
        varianceLines++;
        const inv = await this.prisma.variance_investigations.create({
          data: {
            tenant_id: tenantId, facility_id: count.facility_id, count_id: line.count_id,
            product_id: line.product_id, location_id: line.location_id,
            system_quantity: systemQty, counted_quantity: countedQty,
            variance_quantity: variance,
            variance_percentage: systemQty > 0 ? (variance / systemQty) * 100 : 100,
            status: 'OPEN' as any,
            is_recurring_variance: line.is_repeat_variance || false,
          },
        });
        await this.logEvent(tenantId, count.facility_id, BigInt(id), 'VARIANCE_DETECTED', userId, { investigationId: inv.investigation_id, variance });

        // GAP-3.1: Auto-generate recount if threshold says RECOUNT
        if (thresholdEval.action === 'RECOUNT') {
          await this.prisma.inventory_counts.create({
            data: {
              tenant_id: tenantId, facility_id: count.facility_id,
              count_number: `RECOUNT-${count.count_number}-${Date.now()}`,
              count_scope_type: 'LOCATION', count_scope_identifier: line.location_id,
              status: 'READY', description: `Auto-recount for count ${count.count_number}`,
              count_type: 'RECOUNT', parent_count_id: count.count_id,
              excluded_user_id: line.counted_by_user_id,
              is_blind_count: true,
            },
          });
          await this.logEvent(tenantId, count.facility_id, BigInt(id), 'RECOUNT_CREATED', userId, { investigationId: inv.investigation_id });
        }
      }
    }

    // APP-CC-A: State machine — COUNTED → APPROVED/CLOSED
    const newStatus = varianceLines === 0 ? 'CLOSED' : 'COMPLETED';
    const updated = await this.prisma.inventory_counts.update({
      where: { count_id: BigInt(id) },
      data: {
        status: newStatus,
        total_variances: varianceLines,
        total_variance_quantity: totalVarianceQty,
        total_items_counted: lines.length,
        completed_at: new Date(),
      },
    });

    // GAP-6.3: Update product last_counted_at and next_count_due_at
    for (const line of lines) {
      const product = await this.prisma.products.findFirst({ where: { tenant_id: tenantId, product_id: line.product_id } });
      if (product) {
        const freqDays = product.default_cycle_count_frequency_days || 30;
        const nextDue = new Date();
        nextDue.setDate(nextDue.getDate() + freqDays);
        await this.prisma.products.update({
          where: { product_id: line.product_id },
          data: { last_counted_at: new Date(), next_count_due_at: nextDue },
        });
      }
    }

    await this.logEvent(tenantId, count.facility_id, BigInt(id), newStatus === 'CLOSED' ? 'COUNT_CLOSED' : 'COUNT_COMPLETED', userId, { varianceLines, autoApprovedLines });
    return updated;
  }

  // GAP-2.1: Apply inventory adjustment — update on_hand, create transaction, create inventory_adjustments record
  private async applyInventoryAdjustment(
    tenantId: string, facilityId: bigint, line: any,
    systemQty: number, countedQty: number, variance: number,
    userId: string, approvalType: string,
  ) {
    // Update on_hand
    await this.prisma.inventory_on_hand.updateMany({
      where: { tenant_id: tenantId, product_id: line.product_id, location_id: line.location_id },
      data: { quantity_on_hand: countedQty },
    });
    // Create inventory transaction
    await this.prisma.inventory_transactions.create({
      data: {
        tenant_id: tenantId, facility_id: facilityId,
        transaction_type: 'CYCLE_COUNT', transaction_status: 'COMPLETED',
        reference_type: 'CYCLE_COUNT', reference_id: line.count_id,
        product_id: line.product_id, from_location_id: line.location_id, to_location_id: line.location_id,
        quantity: variance, uom_id: BigInt(1),
        notes: `${approvalType} from cycle count`,
      },
    });
    // GAP-2.1: Create inventory_adjustments record
    const adjType = countedQty > systemQty ? 'INCREASE' : (countedQty < systemQty ? 'DECREASE' : 'ZERO');
    await this.prisma.inventory_adjustments.create({
      data: {
        tenant_id: tenantId, facility_id: facilityId,
        adjustment_number: `CC-ADJ-${line.count_id}-${line.count_line_id}-${Date.now()}`,
        adjustment_name: `Cycle Count Adjustment`,
        description: `${approvalType} variance adjustment`,
        status: 'APPROVED',
        adjustment_type: adjType,
        reason_code: 'CYCLE_COUNT',
        reference_type: 'CYCLE_COUNT',
        reference_id: line.count_id,
        approved_by_user_id: userId,
        approved_date: new Date(),
        executed_date: new Date(),
        total_lines: 1,
        notes: `System: ${systemQty}, Counted: ${countedQty}, Variance: ${variance}`,
      },
    });
    await this.logEvent(tenantId, facilityId, line.count_id, 'ADJUSTMENT_APPLIED', userId, { lineId: line.count_line_id, systemQty, countedQty, variance });
  }

  // GAP-4: Supervisor review methods
  async getPendingReviews(tenantId: string, facilityId: bigint) {
    return this.prisma.variance_investigations.findMany({
      where: { tenant_id: tenantId, facility_id: facilityId, status: investigation_status.OPEN },
    });
  }

  async approveVariance(tenantId: string, investigationId: bigint, supervisorId: string) {
    const inv = await this.prisma.variance_investigations.findFirst({ where: { tenant_id: tenantId, investigation_id: investigationId } });
    if (!inv) throw new NotFoundException('Investigation not found');
    const systemQty = Number(inv.system_quantity || 0);
    const countedQty = Number(inv.counted_quantity || 0);
    const variance = Math.abs(countedQty - systemQty);
    // Apply adjustment
    await this.applyInventoryAdjustment(tenantId, inv.facility_id, { count_id: inv.count_id, count_line_id: null, product_id: inv.product_id, location_id: inv.location_id }, systemQty, countedQty, variance, supervisorId, 'SUPERVISOR_APPROVED');
    // Update count line if exists
    const line = await this.prisma.inventory_count_lines.findFirst({ where: { tenant_id: tenantId, count_id: inv.count_id, product_id: inv.product_id } });
    if (line) {
      await this.prisma.inventory_count_lines.update({
        where: { count_line_id: line.count_line_id },
        data: { status: 'APPROVED', approved_by: supervisorId, approved_at: new Date() },
      });
    }
    await this.logEvent(tenantId, inv.facility_id, inv.count_id, 'SUPERVISOR_APPROVED', supervisorId, { investigationId });
    return this.prisma.variance_investigations.update({
      where: { investigation_id: investigationId },
      data: { status: investigation_status.RESOLVED, resolved_at: new Date(), investigated_by_name: supervisorId },
    });
  }

  async rejectVariance(tenantId: string, investigationId: bigint, supervisorId: string, reason: string) {
    const inv = await this.prisma.variance_investigations.findFirst({ where: { tenant_id: tenantId, investigation_id: investigationId } });
    if (!inv) throw new NotFoundException('Investigation not found');
    await this.logEvent(tenantId, inv.facility_id, inv.count_id, 'SUPERVISOR_REJECTED', supervisorId, { investigationId, reason });
    return this.prisma.variance_investigations.update({
      where: { investigation_id: investigationId },
      data: { status: investigation_status.CLOSED, resolved_at: new Date(), investigation_notes: reason, investigated_by_name: supervisorId },
    });
  }

  // GAP-3.1: Recount generation
  async requestRecount(tenantId: string, investigationId: bigint, supervisorId: string) {
    const inv = await this.prisma.variance_investigations.findFirst({ where: { tenant_id: tenantId, investigation_id: investigationId } });
    if (!inv) throw new NotFoundException('Investigation not found');
    const originalCount = await this.prisma.inventory_counts.findFirst({ where: { tenant_id: tenantId, count_id: inv.count_id } });
    // Get the user who performed the original count (to exclude them from recount)
    const originalLine = await this.prisma.inventory_count_lines.findFirst({ where: { tenant_id: tenantId, count_id: inv.count_id } });
    const excludedUser = originalCount?.assigned_to_user_id || originalLine?.counted_by_user_id || null;
    const recount = await this.prisma.inventory_counts.create({
      data: {
        tenant_id: tenantId, facility_id: inv.facility_id,
        count_number: `RECOUNT-${inv.count_id}-${Date.now()}`,
        count_scope_type: 'LOCATION', count_scope_identifier: inv.location_id || BigInt(0),
        status: 'READY', description: `Recount for investigation ${investigationId}`,
        count_type: 'RECOUNT', parent_count_id: inv.count_id,
        excluded_user_id: excludedUser,
        is_blind_count: true,
      },
    });
    await this.logEvent(tenantId, inv.facility_id, inv.count_id, 'RECOUNT_CREATED', supervisorId, { investigationId, recountId: recount.count_id });
    return this.prisma.variance_investigations.update({
      where: { investigation_id: investigationId },
      data: { status: investigation_status.OPEN, investigation_notes: 'Recount requested' },
    });
  }

  // GAP-3.3: Recount comparison logic
  async compareRecount(tenantId: string, originalCountId: string, recountCountId: string) {
    const originalLines = await this.prisma.inventory_count_lines.findMany({ where: { tenant_id: tenantId, count_id: BigInt(originalCountId) } });
    const recountLines = await this.prisma.inventory_count_lines.findMany({ where: { tenant_id: tenantId, count_id: BigInt(recountCountId) } });
    const results: any[] = [];
    let allAgree = true;
    for (const origLine of originalLines) {
      const recountLine = recountLines.find(rl => rl.product_id === origLine.product_id && rl.location_id === origLine.location_id);
      if (!recountLine) continue;
      const origQty = Number(origLine.counted_quantity);
      const recountQty = Number(recountLine.counted_quantity);
      const agree = Math.abs(origQty - recountQty) <= 1;
      if (!agree) allAgree = false;
      results.push({ productId: origLine.product_id, originalQty: origQty, recountQty: recountQty, agree });
      // APP-CC-I: If disagree → triple-count
      if (!agree) {
        await this.prisma.inventory_counts.create({
          data: {
            tenant_id: tenantId, facility_id: origLine.facility_id,
            count_number: `TRIPLE-${origLine.count_id}-${Date.now()}`,
            count_scope_type: 'LOCATION', count_scope_identifier: origLine.location_id,
            status: 'READY', description: `Triple count for disagreement`,
            count_type: 'TRIPLE_COUNT', parent_count_id: BigInt(originalCountId),
            is_blind_count: true,
          },
        });
      }
    }
    return { allAgree, results };
  }

  // APP-CC-E: Get audit timeline
  async getAuditTimeline(tenantId: string, countId: string) {
    return this.prisma.cycle_count_events.findMany({
      where: { tenant_id: tenantId, count_id: BigInt(countId) },
      orderBy: { performed_at: 'asc' },
    });
  }

  private async getSystemQuantity(tenantId: string, productId: bigint, locationId: bigint, lotId?: bigint | null): Promise<number> {
    const where: any = { tenant_id: tenantId, product_id: productId, location_id: locationId };
    if (lotId !== undefined && lotId !== null) where.lot_id = lotId;
    const records = await this.prisma.inventory_on_hand.findMany({ where });
    return records.reduce((sum, r) => sum + Number(r.quantity_on_hand || 0), 0);
  }
}
